version: '3'

services:
  dotnet-app:
    image: firma:local
    build:
      dockerfile: Dockerfile
    container_name: dotnet-app
    ports:
      - "5000:80"
    networks:
          - local-network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Firma
    ports:
      - "5432:5432"
    networks:
            - local-network

networks:
    local-network:
        driver: bridge